title: User Guide
description: This documentation is Writtened for Users for COMAKE3.0
theme: just-the-docs

url: https://comakeai.github.io/guide

aux_links:
  Template Repository: https://github.com/comakeai/guide
